### ISSUE TITLE
The VM Link is no longer Available

### ISSUE THREAD

**Issue by sufianhashim** [tidiosky/5grail-emu5gnet#1]
Hello,

I tried to download the VM but it is no longer available, can you upload it again and share a fresh link please?

Regards,
Sofian BK

**Comment by dlrb119** [comment]
Request to Upload VM File for [5grail-emu5gnet](https://github.com/tsylla/5grail-emu5gnet)

Dear tsylla
![Snipaste_2024-03-18_15-30-19](https://github.com/tsylla/5grail-emu5gnet/assets/130294496/2fb64db8-fd34-4619-9dc8-db51ff120728)

First and foremost, thank you for your valuable contributions to the emu5gnet project, which greatly benefit the community. During my study, I realized that having access to a VM file would greatly facilitate environment setup and quick start for users.

Therefore, I am reaching out to kindly request if you could share a VM file tailored for emu5gnet? This would be immensely helpful not just for me but many other users as well.

I understand this may require additional time and effort on your part, but rest assured, this contribution would significantly enhance the community's experience and the project's accessibility.

Looking forward to your reply and once again, thank you for your contributions to the open-source community!

Best wishes,
dlrb

**Comment by dlrb119** [comment]
> Hello,
> 
> I tried to download the VM but it is no longer available, can you upload it again and share a fresh link please?
> 
> Regards, Sofian BK

Hello Sofian BK,

I noticed your message regarding the difficulty in downloading the VM. I'm pleased to inform you that the author has recently updated the repository with a new download link for the VM. 

Please feel free to download it from there. If you encounter any further issues or have any questions, the author has mentioned being open to contact for assistance.

Best regards,
dlrb
