### ISSUE TITLE
VM Link Not Available

### ISSUE THREAD

**Issue by Ravatan** [tidiosky/5grail-emu5gnet#2]
Hello,

I was trying to re-download the VM earlier but it seems like the link are stopped working already, can you update the link again please? thank you so much

**Comment by tsylla** [comment]
Hello,

Yeah, I have noticed that to much late. 

I will update with new link and make you know.

**Comment by tsylla** [comment]
Hello,
The VM link has been updated.

You can download the VM :) .

**Comment by tsylla** [comment]
This issue can be closed now.
